finances/urls.py
from django.conf.urls import patterns, include, url
import django.contrib.auth.views

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'finances.views.home', name='home'),
    url(r'^gifts/', include('gifts.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    # manage login & logout
    url(r'^login/$', django.contrib.auth.views.login),
    url(r'^logout/$', django.contrib.auth.views.logout, name = 'logout'),
                       
)

gifts/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('gifts.views',
    url(r'^$', 'index', name = 'home'),
    url(r'^contacts/$', 'contacts', name = 'contacts'),
    url(r'^donations/$', 'donations', name = 'donations'),
    url(r'^asks/$', 'asks', name = 'asks'),
    url(r'^contacts/(?P<contact_id>\d+)/', 
        'contact_record', name = 'contact_record'),
    url(r'^asks/(?P<ask_id>\d+)/', 
        'ask_record', name = 'ask_record'),
    url(r'^newask/(?P<ask_id>\d+)/', 
        'newask', name = 'newask'),
    url(r'^search/$', 'search', name = 'search'),
    url(r'^import/$', 'import_csv', name = 'import'),
    url(r'^combine/$', 'combine', name = 'combine'),
)

gifts/models.py
from django.db import models

RELATIONSHIP_CHOICES = (
    ('FRIEND', 'Friend'),
    ('FAMLIY', 'Family'),
    ('ALUMNUS', 'Alumnus/Alumna'),
    ('UNDERGRAD', 'Undergrad'),
    ('GRADSTUDENT', 'Grad Student'),
)


class Contact(models.Model):

    # essential info
    name = models.CharField(max_length = 255)

    # contact info
    street = models.CharField(max_length = 255, blank = True)
    city = models.CharField(max_length = 127, blank = True)
    state = models.CharField(max_length = 127, blank = True)
    postcode = models.CharField(max_length = 63, blank = True)
    country = models.CharField(max_length = 63, blank = True)
    email = models.EmailField(max_length = 254, blank = True)

    # interesting info
    relationship = models.CharField(max_length = 15, blank = True,
                                    choices = RELATIONSHIP_CHOICES)
    point_person = models.CharField(max_length = 127, blank = True)
    comment = models.CharField(max_length = 2047, blank = True)

    def __unicode__(self):
        return self.name

class Donation(models.Model):

    # essential info
    contact = models.ForeignKey('Contact')
    date = models.DateField()
    amount = models.DecimalField(max_digits = 12, decimal_places = 2)

    # matching information
    matching_funds = models.BooleanField(default = False)
    matching_source = models.CharField(max_length = 255, blank = True)

    # donor-provided info
    publish = models.BooleanField(default = False)    
    comments = models.CharField(max_length = 2047, blank = True)
    referrer = models.CharField(max_length = 255, blank = True)

    # administrative info
    confirmation_number = models.IntegerField(blank=True,null=True)
    fund_number = models.CharField(max_length = 31, null = True, blank = True)

    def __unicode__(self):
        return "${0:} - {1:}".format(self.amount, self.date)

class Ask(models.Model):

    contacts = models.ManyToManyField('Contact')
    date = models.DateField()
    campaign = models.CharField(max_length = 255, blank = True)
    notes = models.CharField(max_length = 2047, blank = True)
    
    def __unicode__(self):
        return self.campaign

gifts/forms.py
from django import forms
from django.forms.extras.widgets import SelectDateWidget
from gifts.models import Ask
import datetime

class SearchForm(forms.Form):
    """Simple form to search contacts based on donations/asks"""

    # what about people who don't have these records
    show_non_donors = forms.BooleanField(required = False)
    show_never_asked = forms.BooleanField(required = False)

    # range of donation amounts
    amount_min = forms.DecimalField(max_digits = 12, decimal_places = 2, required = False)
    amount_max = forms.DecimalField(max_digits = 12, decimal_places = 2, required = False)

    # if you want to set the date field to have a dropdown with a 
    # range of donation dates: allow 2007 - current year
    # set the forms.DateField(widget = widget), where
    # year_range = range(2007, datetime.date.today().year + 1)
    # widget = SelectDateWidget(years = year_range)

    donate_date_min = forms.DateField(required = False)
    donate_date_max = forms.DateField(required = False)

    # range of ask dates
    ask_date_min = forms.DateField(required = False)
    ask_date_max = forms.DateField(required = False)

    # require contact information
    has_email = forms.BooleanField(required = False)
    has_address = forms.BooleanField(required = False)


class UploadCSVForm(forms.Form):
    csvfile  = forms.FileField()

class CombineContactForm(forms.Form):

    def __init__(self, *args, **kwargs):
        new_fields  = kwargs.pop('new_fields')
        new_choices = kwargs.pop('new_choices')
        super(CombineContactForm, self).__init__(*args, **kwargs)
        
        for k,v in zip(new_fields, new_choices):
            if k != "id":
                self.fields[k] = forms.ChoiceField(choices = v)
            else:
                self.fields[k] = forms.MultipleChoiceField(widget = forms.MultipleHiddenInput(), 
                                                           initial = zip(*v)[0])

class AskForm(forms.ModelForm):
    class Meta:
        model = Ask
        exclude = ("contacts")

gifts/views.py
import csv
import datetime
import django_tables2 as tables
from django_tables2 import RequestConfig
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response, render
from gifts.models import Contact, Donation, Ask
from django_tables2.utils import A
from django.contrib.auth.decorators import login_required
from gifts.forms import SearchForm, UploadCSVForm, CombineContactForm, AskForm
from django.core.context_processors import csrf
from django.forms.models import model_to_dict
class MyCheckBoxColumn(tables.CheckBoxColumn):
    header = tables.Column.header

class ContactTable(tables.Table):
    name = tables.LinkColumn("contact_record", args=[A("pk")])

    class Meta:
        model = Contact
        exclude = ('id', )
        attrs = {'class': 'paleblue'}

class SingleContactTable(ContactTable):
    class Meta:
        attrs = {'class': 'paleblue'}
        sequence = ('name', 'street')
        orderable = False

class DonationTable(tables.Table):
    id = tables.Column(visible = False)
    contact = tables.LinkColumn("contact_record", args=[A("contact_id")])

    def render_amount(self, value):
        return "%10.2f" % value

    class Meta:
        model = Donation
        attrs = {'class': 'paleblue'}

class SingleDonationTable(DonationTable):
    id = tables.Column(visible = False)
    contact = tables.Column(visible = False)

    class Meta:
        attrs = {'class': 'paleblue'}


class ShortDonationTable(tables.Table):
    date = tables.Column()
    contact = tables.LinkColumn("contact_record", args=[A("contact_id")])
    amount = tables.Column()

    def render_amount(self, value):
        return "%10.2f" % value

    class Meta:
        attrs = {'class': 'paleblue'}
        orderable = False


class AskTable(tables.Table):
    id = tables.Column(visible = False)
    campaign = tables.LinkColumn("ask_record", args=[A("pk")])

    class Meta:
        model = Ask
        sequence = ('campaign',)
        attrs = {'class': 'paleblue'}

@login_required
def index(request):
    donations_table = ShortDonationTable(Donation.objects.order_by('-pk')[:10])
    RequestConfig(request, paginate = False).configure(donations_table)
    return render(request, 'gifts/index.html', {'donation': donations_table})

@login_required
def contacts(request):
    contact_table = ContactTable(Contact.objects.all())
    RequestConfig(request, paginate = False).configure(contact_table)
    return render(request, 'gifts/contacts.html', {'contact': contact_table})

@login_required
def donations(request):
    donations_table = DonationTable(Donation.objects.all())
    RequestConfig(request, paginate = False).configure(donations_table)
    return render(request, 'gifts/donations.html', {'donation': donations_table})

@login_required
def contact_record(request, contact_id):
    contact_table = SingleContactTable(Contact.objects.filter(pk=contact_id))
    donation_table = SingleDonationTable(Donation.objects.filter(contact_id=contact_id))
    ask_table = AskTable(Ask.objects.filter(contacts=contact_id))
    RequestConfig(request, paginate = False).configure(contact_table)
    RequestConfig(request, paginate = False).configure(donation_table)
    RequestConfig(request, paginate = False).configure(ask_table)
    return render(request, 'gifts/contact_detail.html', 
                  {'contact': contact_table,
                   'donation': donation_table,
                   'ask': ask_table})

@login_required
def ask_record(request, ask_id):
    ask_table = AskTable(Ask.objects.filter(pk = ask_id))
    contact_table = SingleContactTable(Contact.objects.filter(ask__pk=ask_id))
    RequestConfig(request, paginate = False).configure(contact_table)
    RequestConfig(request, paginate = False).configure(ask_table)
    return render(request, 'gifts/ask_detail.html', 
                  {'contact': contact_table,
                   'ask': ask_table})
                   
@login_required
def asks(request):
    ask_table = AskTable(Ask.objects.all())
    RequestConfig(request, paginate = False).configure(ask_table)
    return render(request, 'gifts/asks.html', {'ask_table': ask_table})

@login_required
def search(request):
    # results start as an empty table of the correct type
    results = ContactTable([]) 
    if request.method == 'POST': # If the form has been submitted...
        form = SearchForm(request.POST) # A form bound to the POST data
        if form.is_valid(): # All validation rules pass

            query  = Contact.objects.all()

            if form.cleaned_data['has_email']:
                query = query.exclude(email__exact = '')

            if form.cleaned_data['has_address']:
                query = query.exclude(street__exact = '',
                                      city__exact = '',
                                      country__exact = '')

            # now figure out which donations match the critera

            if form.cleaned_data['show_non_donors']:
                query = query.filter(donation__isnull = True)
            else:
                query = query.filter(donation__isnull = False)

            # decide how to do the date range
            has_amt_min = form.cleaned_data['amount_min'] is not None
            has_amt_max = form.cleaned_data['amount_max'] is not None

            if has_amt_min and not has_amt_max:
                query = query.filter(donation__amount__gte = 
                                     form.cleaned_data['amount_min'])

            if has_amt_max and not has_amt_min:
                query = query.filter(donation__amount__lte = 
                                     form.cleaned_data['amount_max'])

            if has_amt_min and has_amt_max:
                query = query.filter(donation__amount__range = 
                                     (form.cleaned_data['amount_min'],
                                      form.cleaned_data['amount_max']))

            # do the donation date range

            if form.cleaned_data['donate_date_min'] is not None:
                query = query.filter(donation__date__gte = 
                                     form.cleaned_data['donate_date_min'])

            if form.cleaned_data['donate_date_max'] is not None:
                query = query.exclude(donation__date__gt = 
                                     form.cleaned_data['donate_date_max'])

            # figure out which asks match the critera

            if form.cleaned_data['show_never_asked']:
                query = query.filter(ask__isnull = True)
            else:
                query = query.filter(ask__isnull = False)

            if form.cleaned_data['ask_date_min'] is not None:
                query = query.filter(ask__date__gte = 
                                     form.cleaned_data['ask_date_min'])

            if form.cleaned_data['ask_date_max'] is not None:
                query = query.exclude(ask__date__gt = 
                                     form.cleaned_data['ask_date_max'])
            
            query = query.distinct()

            # maybe we want a CSV file

            if "download" in request.POST:
                response = HttpResponse(mimetype='text/csv')
                response['Content-Disposition'] = 'attachment;filename="gifts_search.csv"'
                writer = csv.writer(response)
                writer.writerow(["name","street", "city", "state", 
                                 "postcode", "country", "email"])
                for contact in query:
                    writer.writerow([contact.name, 
                                     contact.street,
                                     contact.city,
                                     contact.state,
                                     contact.postcode,
                                     contact.country,
                                     contact.email])
                return response

            elif "newask" in request.POST and query:
                newask = Ask(date = datetime.date.today())
                newask.save()
                for contact in query:
                    newask.contacts.add(contact)
                newask.save()
                return HttpResponseRedirect("/gifts/newask/%s" % (newask.id))

            # or maybe we just want to see the results
            else:
                results = ContactTable(query)


    else:
        form = SearchForm() # An unbound form
    

    RequestConfig(request, paginate = False).configure(results)
    c = {'form': form,
         'results': results}
    c.update(csrf(request))

    return render(request, 'gifts/search.html', c)

@login_required
def newask(request, ask_id):

    a = Ask.objects.get(pk = ask_id)

    if request.method == 'POST':
        form = AskForm(request.POST, instance=a)
        form.save()
        return HttpResponseRedirect("/gifts/asks/")
    else:
        form = AskForm(instance=a)
        c = {'form': form}
        c.update(csrf(request))
        return render(request, 'gifts/newask.html', c)

@login_required
def import_csv(request):
    if request.method == 'POST': # If the form has been submitted...
        print(request.FILES)
        form = UploadCSVForm(request.POST, request.FILES) # A form bound to the POST/File data
        if form.is_valid(): # All validation rules pass

            new_contacts = ContactTable([])
            new_donations = DonationTable([])

    else:
        form = UploadCSVForm() # An unbound form

        new_contacts = ContactTable([])
        new_donations = DonationTable([])

    c = {'form': form,
         'new_donations': new_donations,
         'new_contacts': new_contacts}
    c.update(csrf(request))

    return render(request, 'gifts/import.html', c)

@login_required
def combine(request):

    if request.method == "POST":

        if len(request.POST.getlist('id')) < 2:
            return HttpResponseRedirect("/gifts/contacts/")
        
        # first get the set of contacts that we're going to merge

templates/gifts/ask_detail.html
{% extends "base.html" %}
{% load render_table from django_tables2 %}

{% block title%}Ask Detail{% endblock %}

{% block content %}
<h2>Ask</h2>
{% render_table ask %}

<h2>Contacts Asked</h2>
{% render_table contact %}

{% endblock %}

{% block footer %}{% endblock %}

templates/gifts/asks.html
{% extends "base.html" %}
{% load render_table from django_tables2 %}

{% block title%}Table{% endblock %}

{% block content %}
{% render_table table %}
{% endblock %}

{% block footer %}{% endblock %}

templates/gifts/combine.html
{% extends "base.html" %}
{% load render_table from django_tables2 %}

{% block title%}Combine Contacts{% endblock %}

{% block content %}
<h2>Combine Contacts</h2>
{% render_table table %}

<form action="/gifts/combine/" method="post">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Submit" />
</form>

{% endblock %}


{% block footer %}{% endblock %}

templates/gifts/contact_detail.html
{% extends "base.html" %}
{% load render_table from django_tables2 %}

{% block title%}Contact Detail{% endblock %}

{% block content %}
<h2>Contact Info</h2>
{% render_table contact %}

<h2>Donations</h2>
{% render_table donation %}

<h2>Asks</h2>
{% render_table ask %}

{% endblock %}

{% block footer %}{% endblock %}

templates/gifts/contacts.html
{% extends "base.html" %}
{% load render_table from django_tables2 %}

{% block title%}Contacts{% endblock %}

{% block content %}
<h2>All Contacts</h2>
{% render_table contact %}
{% endblock %}

{% block footer %}{% endblock %}

templates/gifts/donations.html
{% extends "base.html" %}
{% load render_table from django_tables2 %}

{% block title%}Donations{% endblock %}

{% block content %}
<h2>All Donations</h2>
{% render_table donation %}
{% endblock %}

{% block footer %}{% endblock %}

templates/gifts/import.html
{% extends "base.html" %}
{% load render_table from django_tables2 %}

{% block title%}Import{% endblock %}

{% block content %}

<h2>Import CSV File</h2>

<p>Please note, this page doesn't do anything to the database yet.</p>

<form enctype="multipart/form-data" action="" method="post">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Upload CSV File" />
</form>

<h2>New Contacts</h2>
{% render_table new_contacts %}

<h2>New Donations</h2>
{% render_table new_donations %}

{% endblock %}

templates/gifts/index.html
{% extends "base.html" %}
{% load render_table from django_tables2 %}

{% block title%}Recent Gifts{% endblock %}

{% block content %}
<h2>Recent Donations</h2>
{% render_table donation %}
{% endblock %}

{% block footer %}{% endblock %}

templates/gifts/newask.html
{% extends "base.html" %}
{% load render_table from django_tables2 %}
{% block title%}Search Form{% endblock %}

{% block content %}
<h2>Search Form</h2>
<form action="" method="post">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Submit" />
</form>

{% endblock %}

templates/gifts/search.html
{% extends "base.html" %}
{% load render_table from django_tables2 %}
{% block title%}Search Form{% endblock %}

{% block content %}
<h2>Search Form</h2>
<form action="/gifts/search/" method="post">{% csrf_token %}

  {{ form.non_field_errors }}

  <h3>Donation Constraints</h3>

  <table>
    <tr>
      <td></td>
      <td>{{ form.amount_min.errors }}</td>
      <td></td>
      <td>{{ form.amount_max.errors }}</td>
    </tr>
    <tr>
      <td width="350px"><label for="id_amount_min">Has donated an amount in the range:</label></td>
      <td>{{ form.amount_min }}</td>
      <td><label for="id_amount_max"> -- </label></td>
      <td>{{ form.amount_max }}</td>
    </tr>
    <tr>
      <td width="350px"><label for="id_donate_date_min">Has made a donation more recently than:</label></td>
      <td>{{ form.donate_date_min }}</td>
      <td></td>
      <td>{{ form.donate_date_min.errors }}</td>
    </tr>    
    <tr>
      <td width="350px"><label for="id_donate_date_max">Has not made a donation more recently than:</label></td>
      <td>{{ form.donate_date_max }}</td>
      <td></td>
      <td>{{ form.donate_date_max.errors }}</td>
    </tr>    
    <tr>
      <td width="350px"><label for="id_show_non_donors">Show only contacts who have never donated:</label></td>
      <td>{{ form.show_non_donors }}</td>
      <td></td>
      <td>{{ form.show_non_donors.errors }}</td>
    </tr>
  </table>




  <h3>Ask Constraints</h3>
  <table>
    <tr>
      <td width="350px"><label for="id_ask_date_min">Has been asked more recently than:</label></td>
      <td>{{ form.ask_date_min }}</td>
      <td></td>
      <td>{{ form.ask_date_min.errors }}</td>
    </tr>    
    <tr>
      <td width="350px"><label for="id_ask_date_max">Has not been asked more recently than:</label></td>
      <td>{{ form.ask_date_max }}</td>
      <td></td>
      <td>{{ form.ask_date_max.errors }}</td>
    </tr>    
    <tr>
      <td width="350px"><label for="id_show_never_asked">Show only contacts who have never been asked:</label></td>
      <td>{{ form.show_never_asked }}</td>
      <td></td>
      <td>{{ form.show_never_asked.errors }}</td>
    </tr>
  </table>


  <h3>Contact Constraints</h3>

  <table>
    <tr>
      <td width="350px"><label for="id_has_email">Show only contacts who have an email address:</label></td>
      <td>{{ form.has_email }}</td>
      <td></td>
      <td>{{ form.has_email.errors }}</td>
    </tr>
    <tr>
      <td width="350px"><label for="id_has_address">Show only contacts who have a postal address:</label></td>
      <td>{{ form.has_address }}</td>
      <td></td>
      <td>{{ form.has_address.errors }}</td>
    </tr>
  </table>

  <br>

  <input type="submit" value="Display" />
  <input type="submit" name = "download" value="Download" />
  <input type="submit" name = "newask" value="New Ask" />
</form>

<h2>Matching Records</h2>
{% render_table results %}

{% endblock %}